
// Generated May 29, 2018 1:23:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tokens generated by hbm2java
 */
@Entity
@Table(name="tokens"
    ,catalog="lpc"
)
public class Tokens  implements java.io.Serializable {


     private Integer idTokens;
     private String descricao;

    public Tokens() {
    }

    public Tokens(String descricao) {
       this.descricao = descricao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTokens", unique=true, nullable=false)
    public Integer getIdTokens() {
        return this.idTokens;
    }
    
    public void setIdTokens(Integer idTokens) {
        this.idTokens = idTokens;
    }

    
    @Column(name="descricao", length=45)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


